### ISSUE TITLE
Deploy Elasticsearch and Kibana test

### ISSUE THREAD

**Issue by ivan-unfolds** [TechforgoodCAST/rockerbox#3]
We have an initial setup locally with Elasticsearch, Kibana using Gingerbread's forum's data. It would be good to deploy this so we can share it with rest of team and for user testing.

**Comment by suninthesky** [comment]
I think @drkane looked into hosting options for Elasticsearch a while ago, he might have some suggestions.

**Comment by andrewMacmurray** [comment]
http://elastic-rocker.herokuapp.com

**Comment by drkane** [comment]
I wonder if it's worth looking at a shared CAST hosted elasticsearch that we can use more permanently? I'd like to find somewhere for `find-that-charity` to sit, but the use case is slightly different - it's a fairly big datastore that needs write access (updated once a month probably), but the reads would be fairly low.
